import localFont from "next/font/local";
import "./globals.css";
import QueryClientWrapper from "./components/QueryClientSomething";
import { Toaster } from "@/components/ui/toaster";
import { seedDatabase } from "@/lib/database";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
      // seedDatabase();
  return (
    <QueryClientWrapper>
      <html lang="en">
        <body
          className='bg-zinc-900 text-white'
        >
          {children}
          <Toaster />
        </body>
      </html>
    </QueryClientWrapper>
  );
}
